name: ride_booking_app
description: "Basic Ride Booking App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  json_annotation: ^4.9.0
  flutter_dotenv: ^5.2.1
  freezed_annotation: ^2.4.4
  go_router: ^14.8.1
  another_flushbar: ^1.12.30
  intl: ^0.20.2
  google_maps_flutter: ^2.12.1
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  injectable_generator: ^2.7.0
  freezed: ^2.5.8
  mocktail: ^1.0.4
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - .env

